language: minimal
services:
  - docker
script:
  - docker --version
  - docker-compose --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed dimasmds/udagram-api-feed:latest
  - docker tag udagram-api-user dimasmds/udagram-api-user:latest
  - docker tag udagram-frontend dimasmds/udagram-frontend:latest
  - docker tag udagram-reverseproxy dimasmds/udagram-reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dimasmds/udagram-api-feed
  - docker push dimasmds/udagram-api-user
  - docker push dimasmds/udagram-frontend
  - docker push dimasmds/udagram-reverseproxy
